name: flutter_boost_cli
description:  A CLI tool to generate Flutter feature modules with provider, model, screen, and service files.
version: 1.0.0
repository: https://github.com/fuadmostafij6/flutter_boost_cli

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
